---
- name: "Configure Cloudwatch Log Agent."
  include: "conf.yml"

- stat: path=/var/log/awslogs-agent-setup.log
  register: agent_setup_log

- name: "Install Cloudwatch Log Agent"
  include: "agent.yml"
  when:
    - agent_setup_log.stat.exists == False

- name: "Restart awslogs service."
  service:
    name: "{{ daemon_name }}"
    state: restarted
    enabled: yes
# TODO(tamsky):
#  when:
#    - not ( agent_service_always_restart == True )
